name: core
description: The Core of the GrowERP frontend.
version: 0.0.1
homepage: https://www.growerp.org
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.1.0
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  meta: ^1.3.0
  image_picker: ^0.8.4
  responsive_framework: ^0.1.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  dropdown_search: ^0.6.3
  printing: ^5.7.2
  pdf: ^3.3.0
  about: ^2.0.0
  rxdart: ^0.27.3
  flutter_phoenix: ^1.0.0
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.6
  date_utils: ^0.2.0

  #NETWORK
  json_annotation: ^4.4.0
  dio: ^4.0.4

  #UTITILES
  freezed_annotation: ^1.1.0
  freezed: ^1.0.1
  connectivity: ^3.0.6
  credit_card_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.2
  very_good_analysis: ^2.0.0
  bloc_test: ^9.0.1
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.4
  json_serializable: ^6.0.1


flutter:
  uses-material-design: true
# from https://www.flaticon.com/
